### ISSUE TITLE
deprecated API in class roi_proposal()?

### ISSUE THREAD

**Issue by chakpongchung** [kevinjliang/tf-Faster-RCNN#1]
roi_proposal_net = roi_proposal(rpn_net, gt_boxes, im_dims, eval_mode, flags)
# roi_proposal_net = roi_proposal(rpn_net, gt_boxes, im_dims, eval_mode)

It seems like you have changed these functions. Would you be willing to share the update?
from Networks.faster_rcnn_networks import rpn, roi_proposal, fast_rcnn

**Comment by kevinjliang** [comment]
Hi! I believe the changes to faster_rcnn_networks (including roi_proposal) have already been pushed. We're trying to move away from using the 'flags' dict as much as possible.

**Comment by chakpongchung** [comment]
The latest one has a new problem in /Development/test_faster_rcnn_networks.ipynb

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a54d5d7b781d> in <module>()
----> 1 from Lib.bbox_overlaps import bbox_overlaps

ImportError: dynamic module does not define module export function (PyInit_bbox_overlaps)

**Comment by kevinjliang** [comment]
Ah, okay. The Development/ folder mostly contains experimental code and testing for debugging. We don't actively maintain any of that code.

I can update that notebook when I get the chance though, if that's of interest.

**Comment by chakpongchung** [comment]
Thank you for your quick response.

I tried to follow the demo page too. Where is the faster_rcnn_clutter.py now?
python faster_rcnn_clutter.py -n [Model num, ex 1] -e [Num of epochs, ex 3]

**Comment by kevinjliang** [comment]
It's been removed. I actually just pushed a rather hefty number of updates yesterday; I was planning on updating the README once I take care of a few other things and hoping no one tried to run the demo until then, but it looks like you beat me to it.

Try running (from Models/):
python faster_rcnn_conv5.py -n 1 -e 5 -i 1

Might take a few hours, but it'll save a bunch of PNGs of the results at Data/clutteredMNIST/Outputs/

**Comment by kevinjliang** [comment]
Still have some instructions I need to add, but for the purposes of the demo, the README has been updated. I've also fixed the iPython notebook you were asking about.

**Comment by chakpongchung** [comment]
Hi Kevin,

Thank you for your update. Just as feedback, now the notebook crashed at 
fast_rcnn_net.get_bbox_refinement().get_shape()

python faster_rcnn_conv5.py -n 1 -e 5 -i 1

is working. I have two 1080TI, can I use two gpu to train it?

**Comment by kevinjliang** [comment]
Notebook appears to be working on my end. Are you talking about line 25?

I believe if you include the flag -g 2 when you run the model, it should use both your GPUs. @dancsalo, confirm?

**Comment by chakpongchung** [comment]
yes, this line:

`fast_rcnn_net.get_bbox_refinement().get_shape()
`
