### ISSUE TITLE
ImportError: No module named TensorBase.tensorbase.base

### ISSUE THREAD

**Issue by hadi-ghnd** [kevinjliang/tf-Faster-RCNN#10]
I'm trying to perform faster-RCNN demo based on this page. When I try to run the model (MNIST) with the command :`python faster_rcnn_conv5.py -n [Model num, ex 1] -e [Num of epochs, ex 5]`, it comes to an error like this:

**File "faster_rcnn_conv5.py", line 16, in <module>
     from Lib.TensorBase.tensorbase.base import Model, Data
 ImportError: No module named TensorBase.tensorbase.base**

How can I add this module?
I have already generated the data.

ubuntu16.04
python 2.7
cuda 8

**Comment by kevinjliang** [comment]
Did you do a recursive clone of the repo? See [Installation instructions](https://github.com/kevinjliang/tf-Faster-RCNN#installation).

**Comment by hadi-ghnd** [comment]
Yes I did. I did exactly the same as the instructions.

**Comment by kevinjliang** [comment]
Have you tried: 

```Shell
git submodule update --init --recursive
```

**Comment by takumusumi** [comment]
tried this command. I got the following error.
fatal: reference is not a tree: dd0973a6c1fc512c717db53c07e1be9139b1181b
Unable to checkout 'dd0973a6c1fc512c717db53c07e1be9139b1181b' in submodule path '../Lib/TensorBase'

**Comment by Carlospek** [comment]
I got the same Error.Did you solve it?

**Comment by Carlospek** [comment]
I got it! 
Error occurs when you use Python2.7 executing this demo.
It should be Python3.6 instead.
