### ISSUE TITLE
ImportError: No module named tqdm

### ISSUE THREAD

**Issue by hadi-ghnd** [kevinjliang/tf-Faster-RCNN#11]
I'm trying to run the demo for MNIST. But when I try this command: `python MNIST.py`, it gets to an error like this:

**ImportError: No module named tqdm**

and when I try to install **tgdm** with `pip install tgdm` it says:
**Could not find a version that satisfies the requirement tgdm (from versions: ) No matching distribution found for tgdm**

It works fine when I try it with python3: `python3 MNIST.py`. How can I do this with python 2.7?

**Comment by hadi-ghnd** [comment]
I'm sorry. It is tqdm but I used to type tgdm.

**Comment by kevinjliang** [comment]
I'm not entirely sure why tqdm isn't working for you with Python 2.7, as I've only used it for Python 3+. That being said, it's not entirely necessary for the code to run; it's just there to add progress bars. If it's causing you too many problems, you can go ahead and just delete all instances of it.

Also, I want to add that this repo was not written to be backwards compatible with Python 2.7, though that's not to say it's not possible to make it so. I haven't done any testing with 2.7, but I suggest looking into Python's `__future__` module.
