### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by hadi-ghnd** [kevinjliang/tf-Faster-RCNN#12]
I'm trying to run `python MNIST.py` with python 2.7, but I get this error:

    File "MNIST.py", line 139, in gen_nCluttered

    embedded[y:y + h, x:x + w] += digit ValueError: operands could not be broadcast together with shapes (23,26) (0,0) (23,26)

It does work with python 3.5. How can I make it work it with python 2?

### This is the part which has the error:

%# Insert digit into blank full size image and get max
        embedded = np.zeros([im_dims[0], im_dims[1]])
        embedded[y:y + h, x:x + w] += digit
        max_val = max(embedded.max(), max_val)

**Comment by wang101** [comment]
Same problem
