### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'vram'

### ISSUE THREAD

**Issue by perpetmon** [kevinjliang/tf-Faster-RCNN#13]
Hi 

i'm newbie in tensorflow
(thank you for this code   it's very nice!)

i try this code

simple demo 
    
cd $tf-FRC_ROOT/Models

# Change flags accordingly (see argparser in main() of Model/faster_rcnn_conv5.py file)
python faster_rcnn_conv5.py -n [Model num, ex 1] -e [Num of epochs, ex 5]

and success it 

but i can't success this code
 python faster_rcnn_resnet50ish.py -n 10 -e 20 -y 'clutteredMNIST.yml'

it see this error:

Overriding default parameters with values from clutteredMNIST.yml file
Traceback (most recent call last):
  File "faster_rcnn_resnet50ish.py", line 299, in <module>
    main()
  File "faster_rcnn_resnet50ish.py", line 290, in main
    model = FasterRcnnRes50(flags, dictionary)
  File "faster_rcnn_resnet50ish.py", line 44, in __init__
    super().__init__(flags_input, flags_input['run_num'], vram=cfg.VRAM, restore=flags_input['restore_num'], restore_slim=flags_input['restore_slim_file'])
TypeError: __init__() got an unexpected keyword argument 'vram'

how i can solve it?  

thank you

**Comment by dancsalo** [comment]
Hi @perpetmon, please clone the most recent version and try again. This 'vram' error was a known but temporary bug. Good luck!

**Comment by perpetmon** [comment]
@dancsalo  thank you for feedback :)

i clone the most recent version and try again ,
i see new error....

when run 

 python faster_rcnn_conv5.py -n 1 -e 5 

error :
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value model/fast_rcnn/fc/fully_connected/weights 

and

run 

python faster_rcnn_resnet50ish.py -n 1 -e 5 -y 'clutteredMNIST.yml'

error :
TypeError: argument of type 'NoneType' is not iterable

run
python faster_rcnn_resnet_fixed.py -n 1 -e 5 -y 'clutteredMNIST.yml'

error:
AttributeError: 'EasyDict' object has no attribute 'WEIGHT_DECAY'

Thank you for answering the question.

**Comment by dancsalo** [comment]
Thanks for the follow-up.

1. conv5 model. Do another pull. That error is now fixed.
2. faster_rcnn_resnet50ish with cluttered MNIST is not designed to work: the resnet model expects a 3 channel input, but cluttered MNIST images have only 1 channel.
3.  The faster_rcnn_resnet_fixed model is still in development, so no good results yet; however, I pushed a change to fix the WEIGHT_DECAY error.

**Comment by perpetmon** [comment]
@dancsalo  

thank you for update! 

1. it's fixed!   thank you!
2. faster_rcnn_resnet50ish with pascal_voc2007.yml  have error

i download pascal_voc2007 dataset and run 

scripts/ python PASCAL_VOC.py

and it's success 
-> pascal_voc2007 

but when run 

Models/python faster_rcnn_resnet50ish.py -n 1 -e 5 -y 'pascal_voc2007.yml' 

error:
   File "../Lib/TensorBase/tensorbase/base.py", line 289, in <dictcomp>
    variables_to_restore = {self.name_in_checkpoint(v): v for v in variables if (self.name_in_checkpoint(v) in variables_to_restore)}
TypeError: argument of type 'NoneType' is not iterable


Thank you for answering question.

+

have you ever train new dataset?

**Comment by dancsalo** [comment]
The error is unfortunately uninformative, but it seems you have not downloaded the imagenet weights for resnet50?

**Comment by perpetmon** [comment]
@dancsalo  

oh! i forgot it 
sorry to the question

i downloaded imagenet weight for resnet50 and success run 
faster_rcnn_resnet50ish with pascal_voc2007.yml 

but when it running, 
it see this error

![2017-05-24 17-23-36](https://cloud.githubusercontent.com/assets/28821539/26393898/345649d4-40a6-11e7-961b-fcd3044bab82.png)
Is it pascal voc image dataset probem?

Thank you

**Comment by perpetmon** [comment]
+

recent code (faster_rcnn_conv5.py  ) isn't work
it can't train model

i run python faster_rcnn_conv5.py -n 1 -e 10 -y 'clutteredMNIST.yml' but

![2017-05-25 16-38-54](https://cloud.githubusercontent.com/assets/28821539/26440850/1374cc22-4169-11e7-91ad-023f1d618eb8.png)

Previous code was work 

Thank you

**Comment by dancsalo** [comment]
Indeed, the previous code was working. Sorry for these errors. I have reverted the code back. For the summer, we won't be making any more edits to this code, as @kevinjliang is away for an internship. Good luck!

**Comment by perpetmon** [comment]
@dancsalo 

Thank you for answering question
I really appreciate you!

**Comment by zlyx525** [comment]
Hi!
Thanks very much for the code.
I am a new learner of deep learning and tensorflow.
I clone the latest version, but I have a similar question when I try to run:
python faster_rcnn_conv5.py -n 1 -e 5
error:
Restoring from clutteredMNIST.yml file
Traceback (most recent call last):
  File "faster_rcnn_conv5.py", line 286, in <module>
    main()
  File "faster_rcnn_conv5.py", line 277, in main
    model = FasterRcnnConv5(flags, dictionary)
  File "faster_rcnn_conv5.py", line 40, in __init__
    super().__init__(flags_input, flags_input['run_num'], vram=cfg.VRAM, restore=flags_input['restore_num'])
TypeError: __init__() got an unexpected keyword argument 'vram'
I find that the class Model only have two argument, so I try to del the last two arguments in File "faster_rcnn_conv5.py", line 40, in __init__
    super().__init__(flags_input, flags_input['run_num'], vram=cfg.VRAM, restore=flags_input['restore_num'])
and try to run with: super().__init__(flags_input, flags_input['run_num']) #change
still error:
raceback (most recent call last):
  File "faster_rcnn_conv5.py", line 286, in <module>
    main()
  File "faster_rcnn_conv5.py", line 277, in main
    model = FasterRcnnConv5(flags, dictionary)
  File "faster_rcnn_conv5.py", line 41, in __init__
    super().__init__(flags_input, flags_input['run_num']) #change
  File "../Lib/TensorBase/tensorbase/base.py", line 202, in __init__
    config_yaml_flags_dict_none = self.check_dict_keys(config_yaml_flags_dict)
  File "../Lib/TensorBase/tensorbase/base.py", line 237, in check_dict_keys
    if key not in config_yaml_flags_dict:
TypeError: argument of type 'int' is not iterable
I think I must not understand super() in "super().__init__(flags_input, flags_input['run_num'], vram=cfg.VRAM, restore=flags_input['restore_num'])" correctly.
How can I solve this error, can you help me?

**Comment by kevinjliang** [comment]
Hi @zlyx525, yes, that was the same problem that @perpetmon had. We patched it (with commit 4a7de4069728e5c89c78ac06993f3edca4595bfb, I believe), but unfortunately we had to roll back a large number commits because of some other issue with one of the resnet models. If you checkout that commit, then the convnet demo should work.

**Comment by zlyx525** [comment]
Thanks very much for your help @kevinjliang , but the problem I have is not the same problem @perpetmon  had. It is a similar one. I fail to run:  **python faster_rcnn_conv5.py -n 1 -e 5** , but perpetmon success it. 
I have checked out the commit 4a7de40, finding that the content in faster_rcnn_config.py and base.py that I have cloned are already consistent, and only the code in the faster_rcnn_resnet50ish.py is not the same. I modify the faster_rcnn_resnet50ish.py according to the commit 4a7de40. Then, I try to run **python faster_rcnn_conv5.py -n 1 -e 5**  again. The same error **TypeError: __init__() got an unexpected keyword argument 'vram'** happened. 
What does the argument **vram** used for, can I just del it ?
Looking forward to your reply!

**Comment by kevinjliang** [comment]
If you're trying to run `python faster_rcnn_conv5.py -n 1 -e 5` as you're saying, you need to make sure you're modifying `faster_rcnn_conv5.py`, not `faster_rcnn_resnet50ish.py`. 

The VRAM argument sets how much of your GPU memory TensorFlow is given. We moved around where it gets set recently, which is probably the source of the confusion.

**Comment by zlyx525** [comment]
Thanks for your patience.

**Comment by zlyx525** [comment]
Thanks for your patience.
