### ISSUE TITLE
fatal: reference is not a tree

### ISSUE THREAD

**Issue by kreid415** [kevinjliang/tf-Faster-RCNN#14]
When I ran "git clone --recursive https://github.com/kevinjliang/tf-Faster-RCNN.git" I received the following error,

fatal: reference is not a tree: dd0973a6c1fc512c717db53c07e1be9139b1181b
Unable to checkout 'dd0973a6c1fc512c717db53c07e1be9139b1181b' in submodule path 'Lib/TensorBase'

**Comment by kevinjliang** [comment]
Odd, it looks like the TensorBase submodule is pointing at a non-existent node. Not sure how that happened. We'll look into it, but it might be some time before we get around to fixing it.

For the time being:
It looks like the commit that TensorBase should actually be pointed at is 49c5930eaa49053dac11cae56f00e764b2b05cc7. If you do the clone without the recursive flag (ie `git clone https://github.com/kevinjliang/tf-Faster-RCNN.git`) and then manually clone the aforementioned TensorBase commit, then it should work.

**Comment by kevinjliang** [comment]
I realize this is about a month late, but it should be fixed now.
