### ISSUE TITLE
 how to get the recall rate?

### ISSUE THREAD

**Issue by hadi-ghnd** [kevinjliang/tf-Faster-RCNN#16]
I have performed the faster rcnn on a dataset and gotten the average precision (**AR**) results as they can be seen at the end of testing. How can I get the recall rate with respect to each precision to draw a precision-recall curve like below?
![untitled](https://user-images.githubusercontent.com/24352869/28871905-f1d7e6c6-779b-11e7-9b6a-224935af02b9.gif)

**Comment by kevinjliang** [comment]
I didn't write code for generating those plots, but the values you need to generate that plot are in lines 134-135 [here](https://github.com/kevinjliang/tf-Faster-RCNN/blob/master/Lib/evaluate_predictions.py).
