### ISSUE TITLE
Problem of Line 44 in file 'tf-Faster-RCNN/Models/faster_rcnn_resnet50ish.py'

### ISSUE THREAD

**Issue by Kongsea** [kevinjliang/tf-Faster-RCNN#17]
Line 44 in file 'tf-Faster-RCNN/Models/faster_rcnn_resnet50ish.py':

> super().__init__(flags_input, flags_input['run_num'], vram=cfg.VRAM, restore=flags_input['restore_num'], restore_slim=flags_input['restore_slim_file'])

This line calls the Model's __init__ function, however, which I found only received two arguments: flags and config_dict.
So this line can run correctly?

Since I use python2, so I cannot test it. I just want to rewrite this project to python2 and I am curious about this line.

So please give me some help. Thank you.

**Comment by kevinjliang** [comment]
Sorry, one of the submodules was pointing at a nonexistent node at one point. Should be fixed now.
