### ISSUE TITLE
bottleneck() arguments

### ISSUE THREAD

**Issue by RomanSteinberg** [kevinjliang/tf-Faster-RCNN#2]
I configured frcnn in docker. But when I start training `faster_rcnn_resnet50ish.py` I've got the following error:
```
Traceback (most recent call last):
  File "faster_rcnn_resnet50ish.py", line 300, in <module>
    main()
  File "faster_rcnn_resnet50ish.py", line 291, in main
    model = FasterRcnnRes50(flags, dictionary)
  File "faster_rcnn_resnet50ish.py", line 44, in __init__
    super().__init__(flags_input, flags_input['run_num'], vram=0.8, restore=flags_input['restore_num'], restore_slim=flags_input['restore_slim_file'])
  File "../Lib/TensorBase/tensorbase/base.py", line 722, in __init__
    self._network()
  File "faster_rcnn_resnet50ish.py", line 83, in _network
    self._faster_rcnn(self.x['TRAIN'], self.gt_boxes['TRAIN'], self.im_dims['TRAIN'], 'TRAIN')
  File "faster_rcnn_resnet50ish.py", line 94, in _faster_rcnn
    res_features = resnet50_reduced(x, is_training=False, output_stride=16)
  File "../Networks/resnet50_reduced.py", line 62, in resnet50_reduced
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 216, in stack_blocks_dense
    net = block.unit_fn(net, rate=1, **unit)
TypeError: bottleneck() argument after ** must be a mapping, not tuple
```
As far as I understand `unit_fn` is the internal name for `bottlenek` routine provided for `Block` construction. So, it should actually take mapping (dict) of arguments to those values. Also I printed the `unit` variable before the following line `net = block.unit_fn(net, rate=1, **unit)` and unit is the tuple (256, 64, 1). 
But I read the `Block` class description and I saw examples of `resnet_utils.stack_blocks_dense` routine call and I understand that `Block` constrcution like this `resnet_utils.Block('block1', bottleneck, [(256, 64, 1)] * 2 + [(256, 64, 2)])` is correct. 

What is the problem? And how can I solve it? Is there anyone who ran this script successfully?

PS: I forgot to say that I changed the `output_stride` value for 16 instead of None. Because it fails the script running.
UPD: last line of the error message log provided.

**Comment by kevinjliang** [comment]
Hi! We're still testing `faster_rcnn_resnet50ish.py` on our end on PASCAL VOC to verify everything works, so I actually haven't finished writing the README instructions for it yet. This isn't immediately obvious from our current instructions, but you need to download the pre-trained weights for ResNet 50 from [here](https://github.com/tensorflow/models/tree/master/slim#Pretrained), if you go with our default configuration settings.

**Comment by RomanSteinberg** [comment]
@kevinjliang I did that actually. But I must notice that I have started training for my own dataset, actually. So, the first thing I am going to do at Monday is to run training on PASCAL VOC. I'll report if it ok or not.

**Comment by kevinjliang** [comment]
Ah okay. In that case, could you include more of the traceback to include the error message as well?

Word of warning if you try to train on PASCAL VOC: we've noticed that the algorithm bugs out and crashes if it doesn't produce any valid anchor boxes. This happens for something like 3 of the PASCAL VOC images that have very narrow dimensions. We'll fix this eventually, but to get around it for the time being, I'd recommend either changing the anchor scales or removing the offending images!

**Comment by RomanSteinberg** [comment]
@kevinjliang I downloaded PascalVOC2007 and tried to run your script like this:
```
python faster_rcnn_resnet50ish.py -n 1 -e 50 -y pascal_voc2007.yml
```
The error message is the same. I updated the first post.

**Comment by dancsalo** [comment]
In reference to @kevinjliang's comment about 3 PASCAL VOC images with narrow dimensions in the training set, I found empirically that the image names are 2848, 6524, 9303.

**Comment by RomanSteinberg** [comment]
Guys, do you think that this error was occured because of some unexpected data? I don't think so, because it crashes on creating resnet stage.

**Comment by kevinjliang** [comment]
It doesn't seem like this error has anything to do with the data. We're running TensorFlow v 1.0.0 at the moment. Perhaps something changed in the update? We'll continue looking into it!
