### ISSUE TITLE
Average Precision for class error

### ISSUE THREAD

**Issue by zlchen6** [kevinjliang/tf-Faster-RCNN#20]
Hello! I run your mnist exmaple.During training ,Average Precision always is zero?(I always follow your step)
Detecting images in VALID set
100%|██████████████████████████████████████| 5000/5000 [00:19<00:00, 254.80it/s]No detections were made
Average Precision for class 1: 0.0
Average Precision for class 2: 0.0
Average Precision for class 3: 0.0
Average Precision for class 4: 0.0
Average Precision for class 5: 0.0
Average Precision for class 6: 0.0
Average Precision for class 7: 0.0
Average Precision for class 8: 0.0
Average Precision for class 9: 0.0
Average Precision for class 0: 0.0
Mean Average Precision on VALID Set: 0.000000

**Comment by kevinjliang** [comment]
Hm, odd. Yeah, that definitely isn't supposed to happen. I just merged a bunch of changes, and there's a good chance something was messed up. I'll look into it when I get the chance.

**Comment by zlchen6** [comment]
Thank you. Look forward to your next reply

**Comment by Jasonsun1993** [comment]
I have the same problem in PASCAL VOC dataset, have you solved the problem?

**Comment by lucidkrish** [comment]
i got this same issue with cluttered MNIST
