### ISSUE TITLE
Test or Eval always predicts error

### ISSUE THREAD

**Issue by zlchen6** [kevinjliang/tf-Faster-RCNN#21]
Hello! Test or Eval accuracy always is zero.I try "faster_rcnn_conv5.py" and "faster_rcnn_resnet50ish.py" always get the same error(accuracy is zero).I also git clone your newest file,but same result. I also see the demo.I hope you run your example MNIST demo again,to find Whether something is wrong .thanks!

**Comment by kevinjliang** [comment]
Hi there. Yes, I'm aware this is currently an issue. I'm looking into it!

**Comment by zlchen6** [comment]
expecting...

**Comment by xistor** [comment]
same problem.Looking forward to your next update.

**Comment by kevinjliang** [comment]
I'm still disentangling what went wrong, but in the meantime, you can use commit b6a5416c184e5e4f059726d2944ebd7111730514:

```Shell
git checkout b6a5
```

**Comment by zlchen6** [comment]
That is great! It could work! I'm also still disentangling what went wrong.
