### ISSUE TITLE
Cannot train ResNet Model on my own DataSet

### ISSUE THREAD

**Issue by MohammedAzizi** [kevinjliang/tf-Faster-RCNN#22]
Hi , 
I'm trying to train my own DataSet of an RGB images with the Resnet model , using the script " **faster_rcnn_resnet50ish.py** " , however the error below occured and I couldn't fix it .. 
"_Restoring TF-Slim-Model
Unsuccessful TensorSliceReader constructor : Failed to find any matchinf files for ../Data_/"
Thank you

**Comment by kevinjliang** [comment]
I'm guessing you currently have the flag for initializing from pre-trained weights flicked True (default value). If that's the case, you need to download them [here](https://github.com/tensorflow/models/tree/master/research/slim#Pretrained) (the one for ResNet V1 50).

**Comment by MohammedAzizi** [comment]
Right Kevin , I needed to download the weight 
Thank you
