### ISSUE TITLE
No images for PascalVOC

### ISSUE THREAD

**Issue by RomanSteinberg** [kevinjliang/tf-Faster-RCNN#3]
I tried to run `faster_rcnn_conv5.py` for PascalVOC and noticed that there are no images in a folder `Images` generated by `PASCAL_VOC.py` script.

**Comment by kevinjliang** [comment]
Yep, we're aware of this. PASCAL VOC is still a work in progress. For the time being, we're just inserting a soft link into the VOC devkit.

**Comment by kevinjliang** [comment]
See commit: 91f9b4661cb1d4efed95a9f74982229b7cf2f6e3

Note: this assumes you have the VOC devkit (or a symlink) in tf-FRCNN_ROOT/Data/. Detailed instructions in the README forthcoming
