### ISSUE TITLE
Shape problem

### ISSUE THREAD

**Issue by RomanSteinberg** [kevinjliang/tf-Faster-RCNN#4]
I prepaired PascalVOC dataset and ran 
```
python faster_rcnn_conv5.py -n 1 -e 50 -y pascal_voc2007.yml
```
It shows a lot of info including following
```
Using GPU 0
conv_1 output: (1, ?, ?, 32)
conv_2 output: (1, ?, ?, 64)
...
fc_1 output: (?, 1024)
fc_2 output: (?, 1024)
fc_1 output: (?, 21)
fc_1 output: (?, 84)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
```
At the end I've got an error
```
Traceback (most recent call last):                                                                         | 0/5011 [00:00<?, ?it/s]
  File "faster_rcnn_conv5.py", line 286, in <module>
    main()
  File "faster_rcnn_conv5.py", line 279, in main
    model.train()
  File "faster_rcnn_conv5.py", line 159, in train
    summary = self._run_train_iter(feed_dict)
  File "faster_rcnn_conv5.py", line 127, in _run_train_iter
    summary, _ = self.sess.run([self.merged, self.optimizer], feed_dict=feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 786, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 972, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 375, 500, 3) for Tensor 'Placeholder:0', which has shape '(1, ?, ?, 1)'
```
Thank you for solving issue #3, but I can fix issues myself if you explain me how it works in your environment and how do you expect it working in the future.

**Comment by kevinjliang** [comment]
As the error message says, `faster_rcnn_conv5.py` is currently configured for a 1-channel input (4th placeholder dimension), while PASCAL VOC is 3 channels (RGB). If you want to use that particular model on RGB, you'd have to change the input placeholders for your images to accept 3 channels. I'd also recommend making the model deeper (more layers) if you want to try running on PASCAL VOC.

**Comment by RomanSteinberg** [comment]
Actually my goal is to run on my own dataset. But I thought I can run it for PASCAL VOC right now.

Sorry, for inconveneice. But the message is not so clear for me :)

**Comment by kevinjliang** [comment]
How many channels is your input? Are your images RGB color (3 channels) or grayscale (1 channel)? The placeholder for the input `x` must match your data. 

My advice on making the model deeper holds true for real images of reasonable size. The 5-layer convolutional model example (`faster_rcnn_conv5.py`) was for cluttered MNIST, which isn't as complex as the typical real, RGB image.

**Comment by RomanSteinberg** [comment]
Yes, it is RGB. I'll decide what to do next: look for another implementation of faster-rcnn or try to contribute in your repo. It depends on estimated time. 

Thank's a lot anyway.

**Comment by kevinjliang** [comment]
I currently have `faster_rcnn_resnet50ish.py` training on PASCAL VOC right now, and given the validation scores, it's looking promising so far. I'll aim to add more detailed instructions to the README this weekend.
