### ISSUE TITLE
I have more than 250GB images for training face detection, is it doable with your implementation?

### ISSUE THREAD

**Issue by chakpongchung** [kevinjliang/tf-Faster-RCNN#6]
The problem is I dont want to put them into one large folder. They are all 3 channels images.

Could you provide a step by step tutorial in your README?

**Comment by kevinjliang** [comment]
If you already have your images elsewhere in your directory system, you can insert a soft link to your data with `ln -s [SRC_DIR] tf-FRCNN_ROOT/Data/Faces/Images`, or something along those lines. This'll save you from having to copy your data set into this repo.

Depending on the dimensions of your images, you may or may not have to adjust the model architecture as well. I'm planning on writing a step-by-step tutorial on PASCAL VOC as an example once I finish some testing on our end.

**Comment by chakpongchung** [comment]
|--tf-Faster-RCNN_ROOT
  |--Data/
    |--[YOUR_DATASET]/
      |--Annotations/
        |--*.txt (Annotation Files: (x1,y1,x2,y2,label))
      |--Images/
        |--*.[png/jpg] (Image files)
      |--Names/
        |--train.txt (List of training data filenames)
        |--valid.txt (List of validation data filenames)
        |--test.txt  (List of testing data filenames)


Do you mean this:

|--tf-Faster-RCNN_ROOT
  |--Data/
    |--[FACES_1]/
      |--Annotations/
        |--*.txt (Annotation Files: (x1,y1,x2,y2,label))
      |--Images/
        |--*.[png/jpg] (Image files)
      |--Names/
        |--train.txt (List of training data filenames)
        |--valid.txt (List of validation data filenames)
        |--test.txt  (List of testing data filenames)
    |--[FACES_2]/
      |--Annotations/
        |--*.txt (Annotation Files: (x1,y1,x2,y2,label))
      |--Images/
        |--*.[png/jpg] (Image files)
      |--Names/
        |--train.txt (List of training data filenames)
        |--valid.txt (List of validation data filenames)
        |--test.txt  (List of testing data filenames)


By the way, I am thinking whether we can setup the travis for testing training module. For example, take a very small data set to test the training module in travis.

That way, whenever people try to contribute to the code, it makes sure it is working first before merge. That green sign also give people confidence to use your amazing work.

So far I have tried 
https://github.com/smallcorgi/Faster-RCNN_TF
https://github.com/CharlesShang/TFFRCNN
The training for in house data is not working. Unless I use the exact same config of the training demo.

**Comment by kevinjliang** [comment]
Close. If you want to train and test on FACES_1 and FACES_2 with separate models, then yes. If you want your model to train on all the train data in FACES_1 + FACES_2 and evaluate on the test data of both as well, you need to find a way to combine those into a single FACES directory.

I'm unfamiliar with Travis, but I can look into it!
