### ISSUE TITLE
ImportError: ../Lib/nms/gpu_nms.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by hadi-ghnd** [kevinjliang/tf-Faster-RCNN#9]
Hi
I'm trying to perform faster-RCNN demo based on [this page](url). When I try to run a sample model with python 3, it comes to errors like this:

> ImportError: ../Lib/nms/gpu_nms.so: undefined symbol: _Py_ZeroStruct

I tried to comment this line:
`from .nms.gpu_nms import gpu_nms`
in nms_wrapprt.py and the error became like this:

> ImportError: ../Lib/nms/cpu_nms.so: undefined symbol: _Py_ZeroStruct

Now when I comment this line also:
`nms.cpu_nms import cpu_nms`

the error changes to this:

> ImportError: ../Lib/bbox_overlaps.so: undefined symbol: _Py_ZeroStruct

What can I do to make this **.so** files to work with python 3?

(Ubuntu 16.04
cuda 8.0
pyhton 2.7 and 3.5)

**Comment by kevinjliang** [comment]
I'm unfamiliar with that error. Are you sure you ran `make` in the `Lib/` directory? If you did, my guess is that it's a packages version issue.

**Comment by hadi-ghnd** [comment]
Yes I did run `make` and it was done with no problems. I have installed **tensorflow** in both python 2 and 3. With python 2 it always says: 

> no module names tensorflow

and with python 3 there is this error with **.so** files.

**Comment by kevinjliang** [comment]
It seems like your system might be confusing package/python versions. As I suggest in the README, Anaconda environments are really handy for keeping track of the right package versions; I/ think you're system is using the wrong Python or NumPy.

**Comment by hadi-ghnd** [comment]
I did install Anaconda once before and it messed up the entire OS python paths and I had to reinstall the whole OS from scratch. Right now I just have installed both python 2.7 and 3.5. 

### This is the result of `pip list`:

appdirs (1.4.3)
apturl (0.5.2)
beautifulsoup4 (4.4.1)
bleach (2.0.0)
blinker (1.3)
Brlapi (0.6.4)
chardet (2.3.0)
checkbox-support (0.22)
command-not-found (0.3)
cryptography (1.2.3)
cycler (0.10.0)
Cython (0.25.2)
decorator (4.0.11)
defer (1.0.6)
easy-dict (0.1.1)
easydict (1.6)
entrypoints (0.2.2)
feedparser (5.1.3)
guacamole (0.9.2)
html5lib (0.999999999)
httplib2 (0.9.1)
idna (2.0)
ipykernel (4.6.1)
ipython (6.0.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
jedi (0.10.2)
Jinja2 (2.8)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
language-selector (0.1)
louis (2.6.4)
lxml (3.5.0)
Mako (1.0.3)
MarkupSafe (0.23)
matplotlib (2.0.0)
mistune (0.7.4)
nbconvert (5.1.1)
nbformat (4.3.0)
notebook (5.0.0)
numpy (1.12.1)
oauthlib (1.0.3)
onboard (1.2.0)
opencv-python (3.2.0.7)
packaging (16.8)
padme (1.1.1)
pandocfilters (1.4.1)
pbr (3.0.0)
pexpect (4.0.1)
pickleshare (0.7.4)
Pillow (3.1.2)
pip (9.0.1)
plainbox (0.25)
prompt-toolkit (1.0.14)
protobuf (3.2.0)
ptyprocess (0.5)
pyasn1 (0.1.9)
pycups (1.9.73)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.20.0)
PyJWT (1.3.0)
pyparsing (2.2.0)
python-apt (1.1.0b1)
python-dateutil (2.6.0)
python-debian (0.1.27)
python-systemd (231)
pytz (2017.2)
pyxdg (0.25)
PyYAML (3.12)
pyzmq (16.0.2)
qtconsole (4.3.0)
reportlab (3.3.0)
requests (2.9.1)
scipy (0.19.0)
screen-resolution-extra (0.0.0)
sessioninstaller (0.0.0)
setuptools (35.0.1)
simplegeneric (0.8.1)
six (1.10.0)
stevedore (1.21.0)
system-service (0.3)
tensorflow-gpu (1.0.1)
terminado (0.6)
testpath (0.3)
tornado (4.5.1)
tqdm (4.11.2)
traitlets (4.3.2)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
unattended-upgrades (0.1)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-gdrive (0.7)
unity-scope-manpages (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
urllib3 (1.13.1)
usb-creator (0.3.0)
virtualenv (15.0.1)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.29.0)
widgetsnbextension (2.0.0)
xdiagnose (3.8.4.1)
xkit (0.0.0)
XlsxWriter (0.7.3
### 
These are the last lines of my `.bashrc` file:

> export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH
> export PYTHONPATH=/home/hadi/Software/caffe/python:$PYTHONPATH
> 
> export PATH=/usr/local/cuda-8.0/bin:$PATH
>  
> export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64"
> export CUDA_HOME=/usr/local/cuda
> 
> export WORKON_HOME=/home/hadi/.virtualenvs
> source /usr/local/bin/virtualenvwrapper.sh

Is there a way to find out what is wrong with the python packages?

**Comment by zhen0827** [comment]
I solved this problem by modifying ./Lib/Makefile
`all:
	python3 setup.py build_ext --inplace
	rm -rf build`
by the way ,in my system, tensorflow is installed in the original python3.5
hope this is helpful

**Comment by kevinjliang** [comment]
To add to @zhen0827, if you set up an Anaconda environment as described in the installation instructions, the system Python will default to Python 3, and the Makefile will work as is!
